# 生产环境配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://47.99.118.208:3306/talent_portrait?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:mysql20240327}

  redis:
    host: 47.99.118.208
    port: 6379
    password: ${REDIS_PASSWORD:redis123}

# MinIO配置
minio:
  endpoint: http://47.99.118.208:9000
  accessKey: ${MINIO_ACCESS_KEY:TZsPKdmWLJJbMNQbpG4V}
  secretKey: ${MINIO_SECRET_KEY:Rcz0p0Ybbm6UVslVx9mmiMACP772iVcRqbjpHxIo}
  bucketName: talent-portrait

# 生产环境日志
logging:
  level:
    com.cgn.talent: info
    org.springframework: warn
