# 开发环境配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/talent_portrait?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456

  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# MinIO配置 - 暂时禁用，使用本地文件存储
minio:
  endpoint: http://localhost:9000
  bucketName: talent-portrait
  tempBucketName: talent-portrait-temp
  accessKey: minioadmin
  secretKey: minioadmin
  assessAddress: http://localhost:9000

# 开发环境日志
logging:
  level:
    com.cgn.talent: debug
