# 生产环境配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.100:3306/talent_portrait?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${DB_USERNAME:talent_user}
      password: ${DB_PASSWORD:Talent@2024}

  redis:
    host: 192.168.1.101
    port: 6379
    password: ${REDIS_PASSWORD:Redis@2024}

# MinIO配置
minio:
  endpoint: http://192.168.1.102:9000
  accessKey: ${MINIO_ACCESS_KEY:talentminio}
  secretKey: ${MINIO_SECRET_KEY:Minio@2024}
  bucketName: talent-portrait

# 生产环境日志
logging:
  level:
    com.cgn.talent: info
    org.springframework: warn
